language: python
python:
    - "3.4"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
script:
    - py.test
after_success:
    - if [[ $ENV == python=3.4* ]]; then
          coveralls;
      fi
